name: Check example code

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  correctness:
    name: OI-wiki Example Code Correctness Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed code files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            docs/**/*.cpp
            docs/**/*.in
            docs/**/*.ans
      - uses: actions/setup-python@v5
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          python-version: '3.10'
          cache: pipenv
      - name: Install Python dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python3
          pipenv install
      - name: Install C++
        if: steps.changed-files.outputs.any_changed == 'true'
        run: sudo apt-get install -y g++
      - name: Make the File list
        if: steps.changed-files.outputs.any_changed == 'true'
        run: echo "${{ steps.changed-files.outputs.all_changed_files }}" > res.txt
      - name: Check the Code
        if: steps.changed-files.outputs.any_changed == 'true'
        run: pipenv run python scripts/test.py 2> stderr.txt

  undefinedbehaviors-ubuntu:
    name: OI-wiki Undefined Behaviors Test - Ubuntu
    needs: correctness
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed code files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            docs/**/*.cpp
            docs/**/*.in
            docs/**/*.ans
      - uses: actions/setup-python@v5
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          python-version: '3.10'
          cache: pipenv
      - name: Install Python dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python3
          pipenv install
      - name: Install C++
        if: steps.changed-files.outputs.any_changed == 'true'
        run: sudo apt-get install -y g++
      - name: Make the File list
        if: steps.changed-files.outputs.any_changed == 'true'
        run: echo "${{ steps.changed-files.outputs.all_changed_files }}" > res.txt
      - name: Check the Code
        if: steps.changed-files.outputs.any_changed == 'true'
        run: pipenv run python scripts/test.py 2> stderr.txt

  undefinedbehaviors-macos:
    name: OI-wiki Undefined Behaviors Test - MacOS
    needs: correctness
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed code files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            docs/**/*.cpp
            docs/**/*.in
            docs/**/*.ans
      - uses: actions/setup-python@v5
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          python-version: '3.10'
          cache: pipenv
      - name: Install Python dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python3
          pipenv install
      - name: Install C++
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          brew install gcc@11
          brew install gcc@12
          brew install gcc@13
      - name: g++ Version
        if: steps.changed-files.outputs.any_changed == 'true'
        run: g++ --version
      - name: Make the File list
        if: steps.changed-files.outputs.any_changed == 'true'
        run: echo "${{ steps.changed-files.outputs.all_changed_files }}" > res.txt
      - name: Check the Code
        if: steps.changed-files.outputs.any_changed == 'true'
        run: pipenv run python scripts/test.py 2> stderr.txt

