name: Check example code

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  correctness:
    name: OI-wiki Example Code Correctness Check
    runs-on: ubuntu-latest
    outputs:
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
      files_to_test: ${{ steps.GetFiles.outputs.files_to_test }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed code files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            docs/**/*.cpp
            docs/**/*.in
            docs/**/*.ans
      - uses: actions/setup-python@v5
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          python-version: '3.10'
          cache: pipenv
      - name: Install Python dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python3
          pipenv install
      - name: Install C++
        if: steps.changed-files.outputs.any_changed == 'true'
        run: sudo apt-get install -y g++
      - name: Make the File list
        if: steps.changed-files.outputs.any_changed == 'true'
        run: echo "${{ steps.changed-files.outputs.all_changed_files }}" > res.txt
      - name: Get Files to Test
        if: steps.changed-files.outputs.any_changed == 'true'
        id: GetFiles
        run: pipenv run python scripts/get_files_to_test.py
      - name: Correctness Check
        if: steps.changed-files.outputs.any_changed == 'true'
        env: 
          FILES_TO_TEST: ${{ steps.GetFiles.outputs.files_to_test }}
        run: pipenv run python scripts/correctness_check.py

  undefinedbehaviors-ubuntu:
    name: OI-wiki Undefined Behaviors Test - Ubuntu
    needs: correctness
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed code files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            docs/**/*.cpp
            docs/**/*.in
            docs/**/*.ans
      - uses: actions/setup-python@v5
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          python-version: '3.10'
          cache: pipenv
      - name: Install Python dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python3
          pipenv install
      - name: Install C++
        if: steps.changed-files.outputs.any_changed == 'true'
        run: sudo apt-get install -y g++
      - name: Make the File list
        if: steps.changed-files.outputs.any_changed == 'true'
        run: echo "${{ steps.changed-files.outputs.all_changed_files }}" > res.txt
      - name: Check the Code
        if: steps.changed-files.outputs.any_changed == 'true'
        run: pipenv run python scripts/test.py 2> stderr.txt

  undefinedbehaviors-macos:
    name: OI-wiki Undefined Behaviors Test - MacOS
    needs: correctness
    if: ${{ needs.correctness.outputs.any_changed == 'true' }}
    runs-on: macos-latest
    steps:
      - name: check output
        env: 
          FILES_TO_TEST: ${{ needs.correctness.outputs.files_to_test }}
        run: echo "${FILES_TO_TEST}"
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed code files
        id: changed-files
        uses: tj-actions/changed-files@v42
        with:
          files: |
            docs/**/*.cpp
            docs/**/*.in
            docs/**/*.ans
      - uses: actions/setup-python@v5
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          python-version: '3.10'
          cache: pipenv
      - name: Install Python dependencies
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python3
          pipenv install
      - name: Install C++
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          brew install gcc@14
      - name: g++ Version
        if: steps.changed-files.outputs.any_changed == 'true'
        run: | 
          g++-14 --version
          clang --version
      - name: Make the File list
        if: steps.changed-files.outputs.any_changed == 'true'
        run: echo "${{ steps.changed-files.outputs.all_changed_files }}" > res.txt
      - name: Undefined Behaviors Check
        if: steps.changed-files.outputs.any_changed == 'true'
        env: 
          FILES_TO_TEST: ${{ needs.correctness.outputs.files_to_test }}
          RUNS_ON: macos-latest
        run: pipenv run python scripts/ub_check_macos.py

